name: .NET 6 CI ğŸš€

on:
  push:
    branches: [ "main, develop" ]
  pull_request:
    branches: [ "main, develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout du code
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: ğŸ“¦ Restore dependencies
        run: dotnet restore ./slf-backend/slf-backend.csproj

      - name: ğŸ—ï¸ Build
        run: dotnet build ./slf-backend/slf-backend.csproj --no-restore --configuration Release

      - name: âœ… Run tests
        run: dotnet test ./slf-backend/slf-backend.csproj --no-build --verbosity normal